#!/usr/bin/env perl

use 5.10.0;

use strict;
use warnings;

use autodie;

use Git;

my $repo = Git->repository;

my $last_import = $repo->command_oneline("rev-parse", "--verify", "cpan/master");

$repo->command_noisy("cpan-import", @ARGV);

my $updated = $repo->command_oneline("rev-parse", "-q", "--verify", "cpan/master");

if ( $last_import ne $updated ) {
    $repo->command_noisy("rebase", "cpan/master");
}
