#!/usr/bin/env perl

use 5.10.0;

use strict;
use warnings;

use autodie;

use Git;

Git->repository->command_noisy('format-patch', 'cpan/master');

__END__

=pod

=head1 NAME

git-cpan-format-patch - Format patches using C<cpan/master> as the origin
reference.

=head1 SYNOPSIS

    % git cpan-format-patch

=head1 DESCRIPTION

This is just like running C<git format-patch cpan/master>.

=head1 VERSION

This document describes git-cpan-format-patch version 0.1.0.

=head1 BUGS AND LIMITATIONS

Please report any bugs or feature requests to
C<bug-git-cpan-patch@rt.cpan.org>, or through the web 
interface at L<http://rt.cpan.org>.
  
=head1 AUTHORS

Yuval Kogman C<< <nothingmuch@woobling.org> >>

Yanick Champoux C<< <yanick@cpan.org> >>

=head1 LICENCE

This module is free software; you can redistribute it and/or
modify it under the same terms as Perl itself. See L<perlartistic>.

=head1 SEE ALSO

L<Git::CPAN::Patch>

L<git-format-patch>

=cut
