#!/usr/bin/env perl

use 5.10.0;

use strict;
use warnings;

use autodie;

use Git;

my $repo = Git->repository;

my $last_import = $repo->command_oneline("rev-parse", "--verify", "cpan/master");

$repo->command_noisy("cpan-import", @ARGV);

my $updated = $repo->command_oneline("rev-parse", "-q", "--verify", "cpan/master");

if ( $last_import ne $updated ) {
    $repo->command_noisy("rebase", "cpan/master");
}

__END__

=pod

=head1 NAME

git-cpan-update - Import the latest version of a module and rebase the current
branch

=head1 SYNOPSIS

    % git cpan-update

=head1 DESCRIPTION

This command runs C<git cpan-import>, and then if C<cpan/master> was updated
runs C<git rebase cpan/master>, bringing your patches up to date with the
upstream.
