#!/usr/bin/env perl

use 5.10.0;

use strict;
use warnings;

use autodie;

use Git;

Git->repository->command_noisy("format-patch", "cpan/master");

__END__

=pod

=head1 NAME

git-cpan-format-patch - Format patches using C<cpan/master> as the origin
reference.

=head1 SYNOPSIS

    % git cpan-format-patch

=head1 DESCRIPTION

This is just like running C<git format-patch cpan/master>.

