#!/usr/bin/env perl -s

use 5.10.0;

use strict;
use warnings;

use autodie;

use Git;

my $repo = Git->repository;

my @patches = $repo->command( 'cpan-format-patch' );

if ( @patches > 1 ) {
    say "Refusing to send more than one patch (each patch email will be in its own RT ticket).";
    say "Run git-cpan-send-email manually to override, or squash your commits.";

    say and unlink($_) for @patches;

    exit 1;
}

$repo->command_noisy( "cpan-send-email", @ARGV, @patches );
