#!/usr/bin/env perl

use 5.10.0;

use strict;
use warnings;

use autodie;

use Git;

my $module = shift || die("Usage: $0 Foo::Bar\n");

Git::command_noisy("init");

my $repo = Git->repository;

$repo->command_noisy("cpan-import", $module);

$repo->command_noisy("checkout", "-t", "-b", "master", "cpan/master");
