#!/usr/bin/env perl -s

use 5.10.0;

use strict;
use warnings;

use autodie;

use Git;

my $repo = Git->repository;

my @patches = $repo->command( 'cpan-format-patch' );

if ( @patches > 1 ) {
    say "Refusing to send more than one patch (each patch email will be in its own RT ticket).";
    say "Run git-cpan-send-email manually to override, or squash your commits.";

    say and unlink($_) for @patches;

    exit 1;
}

$repo->command_noisy( "cpan-send-email", @ARGV, @patches );

__END__

=pod

=head1 NAME

git-cpan-sendpatch - Create patch files and submit them to RT

=head1 SYNOPSIS

    % git cpan-sendpatch

=head1 DESCRIPTION

This command runs C<git cpan-format-patch> and then if there is one patch file
runs C<git cpan-send-email>.

Multiple patches are not sent because C<git send-email> creates a separate
message for each patch file, resulting in multiple tickets.

