#!/usr/bin/env perl

use 5.10.0;

use strict;
use warnings;

use autodie;

use Git;

my $repo = Git->repository;

my $branch = shift || die "Usage: git cpan-squash new-branch-name\n";

my $head = $repo->command_oneline("rev-parse", "--verify", "HEAD");

$repo->command_noisy("checkout", "-b", $branch, "cpan/master");

$repo->command_noisy("merge", "--squash", $head);

say "";

say "Changes squashed onto working directory, commit and run git cpan-sendpatch";

