#!/usr/bin/env perl

use 5.10.0;

use strict;
use warnings;

use autodie;

use Git;
use CPANPLUS;

my $repo = Git->repository;

my $module = $repo->command_oneline("cpan-which");

my $cpan = CPANPLUS::Backend->new;
my $module_obj = $cpan->parse_module( module => $module ) or die("No such module $module");

my $to = 'bug-' . $module_obj->package_name . '@rt.cpan.org';

$repo->command_noisy("send-email", "--to", $to, @ARGV);
