#!/usr/bin/perl

# Do a complete git-ificaiton of BackPAN.  Or give it just a few modules.

use strict;
use warnings;

use Getopt::Long;
use Parse::BACKPAN::Packages;

my %opts;
GetOptions(
    \%opts,
    "backpan:s"
);

my @dists;
if( @ARGV ) {
    @dists = @ARGV;
}
else {
    my $backpan = Parse::BACKPAN::Packages->new();

    # Filter out some garbage the backpan indexer picks up
    @dists = grep !/^[\d._\-]+(\.U)?$/, @{$backpan->distributions};
}

my %backpan_init_opts;
$backpan_init_opts{"--backpan"} = $opts{backpan} if $opts{backpan};

for my $dist (@dists) {
    system "git", "backpan-init" => $dist, %backpan_init_opts, "--mkdir";
    chdir $dist;
    system "git", "gc";
    chdir "..";
}
